version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      dockerfile: 'docker/Dockerfile'
      args:
        uid: ${UID}
    container_name: laravel-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-app
  laravel-mariadb:
    image: mariadb:10.4.3-bionic
    container_name: laravel-mariadb
    restart: always
    ports:
      - 8080:3306
    volumes:
      - /var/lib/mysql
    networks:
      backend:
        aliases:
          - db
    environment:
      - MYSQL_ROOT_PASSWORD=bp1234
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
  laravel-pma:
    image: phpmyadmin/phpmyadmin:5
    container_name: laravel-pma
    depends_on:
      - laravel-mariadb
    restart: always
    ports:
      - 8880:80
    networks:
      backend:
        aliases:
          - phpmyadmin
    environment:
      PMA_HOST: laravel-mariadb
      PMA_PORT: 3306
networks:
  backend:
    name: backend-network
